### ISSUE TITLE
Comparision of different Data Classification algorithms

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#11]
Data Classification Algorithm comparison based on various parameters like input constraints, size, performance etc.

**Comment by JeremiahKamama** [comment]
I would love to help with this

**Comment by NishkarshRaj** [comment]
@JeremiahKamama sure go ahead 😄

**Comment by krkakade** [comment]
Is it still open? Can I work on it?

**Comment by NishkarshRaj** [comment]
@krkakade yes no one has raised a PR to solve this. Go ahead 👍

**Comment by NishkarshRaj** [comment]
Solved by @krkakade
