### ISSUE TITLE
Clustering - K Means

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#24]
I have  programmed for **Clustering - K Means Algorithm** in both R and Python.

Please help me create a explanatory markdown documentation for the same.

Link for the code is [here](https://github.com/NishkarshRaj/100DaysofMLCode/tree/master/5_Clustering/K_Means).

**Comment by neha-shah99** [comment]
Hey, I'm new to open source contribution and learning by starting with documentation. How can I help? Should I update the README inside the Clustering folder?

**Comment by NishkarshRaj** [comment]
@neha-shah99 Yes, create a Readme in the said folder and raise a PR 👍

**Comment by dag2104** [comment]
@NishkarshRaj I want to work on this issue. Please can you guide me?

**Comment by NishkarshRaj** [comment]
@dag2104 This issue has already been resolved. Try another one and I will definitely guide you.

Thanks @neha-shah99 for the contributions 👍
