### ISSUE TITLE
Association Rule - Apriori

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#26]
I have programmed for **Association using Apriori Rules** in both R and Python.

Please help me create a explanatory markdown documentation for the same.

Link for the code is [here](https://github.com/NishkarshRaj/100DaysofMLCode/tree/master/6_Association_Rule/Apriori
).

**Comment by ekdnam** [comment]
@NishkarshRaj is this issue still up-for-grabs?

**Comment by NishkarshRaj** [comment]
@ekdnam yes it is.

**Comment by ekdnam** [comment]
Can you assign me to this issue? I will do it

**Comment by NishkarshRaj** [comment]
I have assigned you the issue @ekdnam 👍

**Comment by swapniljha001** [comment]
Question - Is still issue still unresolved?
Is it wrong to refer to Wikipedia (https://en.wikipedia.org/wiki/Association_rule_learning) and adopt/use it for documentation purposes?

**Comment by NishkarshRaj** [comment]
@swapniljha001 No, it is resolved by @ekdnam 

And no, we can always refer different articles and blogs for our documentation but we must ensure no plagiarism.
