### ISSUE TITLE
Association rule - Eclat

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#27]
I have programmed for **Association Rules using Eclat** in both R and Python.

Please help me create a explanatory markdown documentation for the same.

Link for the code is [here](https://github.com/NishkarshRaj/100DaysofMLCode/tree/master/6_Association_Rule/Eclat)

**Comment by PluckyPrecious** [comment]
Hi @NishkarshRaj,

I'd like to give this a shot is it still **Up-for-Grabs**? If yes, please let me know of extra resource i might need.

Thanks!

**Comment by NishkarshRaj** [comment]
@PluckyPrecious go ahead. All contributions welcomed 👍

**Comment by NishkarshRaj** [comment]
Thanks @PluckyPrecious for your contribution :+1: :100:
