### ISSUE TITLE
List of python packages in one file - requirements.txt

### ISSUE THREAD

**Issue by codingcosmonaut** [NishkarshRaj/100DaysofMLCode#36]
While testing python code samples in this repository, I had to manually install each and every package mentioned among imports. It would be great to have one file where all used packages are listed. That saves so much time.

Recommended solution: requirements.txt which includes all packages used across python files.

**Comment by NishkarshRaj** [comment]
@codingcosmonaut Thanks for the suggestion. 💯 

 Can you work on this issue and create a PR for the same? 👍

**Comment by dylancaponi** [comment]
@NishkarshRaj I'm happy to take this on

**Comment by NishkarshRaj** [comment]
> 
> 
> @NishkarshRaj I'm happy to take this on. Do you agree that one requirements.txt per chapter is the best approach?

@dylancaponi Thanks for the contribution in #37 

I am keeping this issue open for more chapters!

**Comment by NishkarshRaj** [comment]
Thanks everyone for your contributions :+1:

**Comment by NishkarshRaj** [comment]
Thanks @Thanatoz-1 @dylancaponi @codingcosmonaut for this. Closing this issue 👍
