### ISSUE TITLE
Multi Linear Regression in Python

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#4]
Code for Multi Linear Regression In python

**Comment by smritisingh26** [comment]
Hi! Can I work on this?

**Comment by NishkarshRaj** [comment]
Hello @smritisingh26 Thanks for taking your time to see this issue.
Actually this issue has already been solved but I forgot to close this.
Check the code [here](https://github.com/NishkarshRaj/100DaysofMLCode/tree/master/3_Regression/Multi_Linear_Regression/Python)

If you can add something thats missing in the code or can make a small writeup explaining the above code in a markdown file, feel free to raise a PR for the same 👍

**Comment by swapniljha001** [comment]
I believe this issue needs to be closed.

**Comment by NishkarshRaj** [comment]
@swapniljha001 Thanks! 👍
