### ISSUE TITLE
SimpleImputer in Chapter2/missing_data.py is failing

### ISSUE THREAD

**Issue by codingcosmonaut** [NishkarshRaj/100DaysofMLCode#51]
I am getting this error:
`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

**Comment by codingcosmonaut** [comment]
Fixed it with the pull request #52

**Comment by NishkarshRaj** [comment]
> 
> 
> I am getting this error:
> `ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

I did not check that before merging previous PR due to hectic start to HF. 😭 

Thanks for raising the issue and making the necessary changes 😄
