### ISSUE TITLE
Writeup for Polynomial Linear Regression

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#6]
I have uploaded the code for Polynomial Linear Regression. If someone wants to contribute, they can provide a writeup about the same.

**Comment by JeremiahKamama** [comment]
I can work on this too

**Comment by NishkarshRaj** [comment]
@JeremiahKamama sure, go ahead 👍

**Comment by pragyakapoor** [comment]
Hey, do you still need to get this done?

**Comment by NishkarshRaj** [comment]
@pragyakapoor This one is completed by @JeremiahKamama !

Closing this issue.
