### ISSUE TITLE
Pull request For HacktoberFest Problem

### ISSUE THREAD

**Issue by UdayKiranPadhy** [NishkarshRaj/100DaysofMLCode#60]
**Is your feature request related to a problem? Please describe.**
Hey , I Submitted the pull request for hacktober fest , Before I tell you that , you closed it.
https://github.com/NishkarshRaj/100DaysofMLCode/pull/44
Please Lable it as hactoberfest and hacktoberfest-accpted

**Describe the solution you'd like**
Please , Lable it as "hacktoberfest" and "hacktoberfest-accepted"
Open the link 
https://github.com/NishkarshRaj/100DaysofMLCode/pull/44
and on the right side there is a lable tab and please add it.

**Comment by NishkarshRaj** [comment]
Thanks alot for raising an issue in this repository :+1: We will soon give a follow up.

**Comment by UdayKiranPadhy** [comment]
Is there any way to track the progress , Please Bro Can you make it fast .

**Comment by UdayKiranPadhy** [comment]
Hey Please Bro can you make it a bit fast , it just takes few seconds to do that , please . If it happens may be i may not be one of 70,000 participates

**Comment by NishkarshRaj** [comment]
@UdayKiranPadhy The labels are not required for Hacktoberfest.

Although I have added it to your PR. DigitalOcean automatically tracks GitHub PRs once you have registered for the event.
