### ISSUE TITLE
Writeup for Decision Tree Regression

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#8]
Code for Decision Tree Regression has been completed but explanation for same in both R and Python is needed. If someone is open to write an explanation in Markdown file, reply to this issue and I will assign the same to you 👍

**Comment by JeremiahKamama** [comment]
I would love to write an explanation but in Python

**Comment by NishkarshRaj** [comment]
@JeremiahKamama sure. 
Raise a PR with the explanation and I will review it 😄

**Comment by NishkarshRaj** [comment]
Thanks @JeremiahKamama for working on this.
