### ISSUE TITLE
Random Forest Regression

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/100DaysofMLCode#9]
Code for Random Forest Regression has been completed but explanation for same in both R and Python is needed. If someone is open to write an explanation in Markdown file, reply to this issue and I will assign the same to you 👍

**Comment by srv48** [comment]
I am ready to add the required description

**Comment by NishkarshRaj** [comment]
Sure @srv48 
Feel free to fork the repository and add the description. 
Make a PR for the same and I'll gladly review it 👍

**Comment by tushaardwivedi** [comment]
Hey, I'm interested in writing the Markdown file for explanation. Still open?

**Comment by NishkarshRaj** [comment]
@tushaardwivedi Yes! Its still open to work 👍

**Comment by NishkarshRaj** [comment]
Solved by @tushaardwivedi in #18
